"""Background runner for PJob execution.

This module is invoked as a detached subprocess to run a PJob in the background.
"""

from __future__ import annotations

import json
import sys
from datetime import datetime, timezone


def run_pjob_in_background(
    pjob_code: str,
    execution_id: str,
    overrides_json: str | None = None,
    keep_temp: bool = False,
) -> int:
    """Execute a PJob in background, managing state file from start to finish.

    Args:
        pjob_code: PJob code to execute.
        execution_id: Unique execution ID (generated by the CLI layer).
        overrides_json: JSON string of Overrides dict (optional).
        keep_temp: Whether to keep temporary files.

    Returns:
        Exit code (0 for success, 1 for failure).
    """
    from zima.execution.executor import PJobExecutor
    from zima.execution.history import ExecutionHistory
    from zima.models.pjob import Overrides

    overrides = Overrides()
    if overrides_json:
        try:
            overrides = Overrides.from_dict(json.loads(overrides_json))
        except Exception:
            pass

    executor = PJobExecutor()
    started_at = datetime.now(timezone.utc).astimezone().isoformat()

    # Ensure state file exists (CLI should have created it, but be defensive)
    history = ExecutionHistory()
    state = history.get_runtime_state(pjob_code, execution_id)
    if state is None:
        state = {
            "execution_id": execution_id,
            "pjob_code": pjob_code,
            "status": "running",
            "pid": None,
            "command": [],
            "started_at": started_at,
            "finished_at": None,
            "duration_seconds": None,
            "returncode": None,
            "stdout_preview": "",
            "stderr_preview": "",
            "error_detail": "",
            "log_path": "",
            "agent": "",
            "workflow": "",
        }
        history.write_runtime_state(pjob_code, execution_id, state)

    result = executor.execute(
        pjob_code=pjob_code,
        overrides=overrides,
        dry_run=False,
        keep_temp=keep_temp,
    )

    # Update state file with completion data
    stdout_preview = result.stdout[:500] + "..." if len(result.stdout) > 500 else result.stdout
    stderr_preview = result.stderr[:500] + "..." if len(result.stderr) > 500 else result.stderr
    finished_at = datetime.now(timezone.utc).astimezone().isoformat()

    history.update_runtime_state(
        pjob_code,
        execution_id,
        status=result.status.value,
        returncode=result.returncode,
        finished_at=finished_at,
        duration_seconds=result.duration_seconds,
        stdout_preview=stdout_preview,
        stderr_preview=stderr_preview,
        error_detail=result.error_detail[:2000] if result.error_detail else "",
        scan_pr_result=result.scan_pr_result,
    )

    return 0 if result.status.value == "success" else 1


def main() -> int:
    """CLI entry point for background runner."""
    import argparse

    parser = argparse.ArgumentParser(description="Run a PJob in the background")
    parser.add_argument("pjob_code", help="PJob code to execute")
    parser.add_argument("--execution-id", required=True, help="Unique execution ID")
    parser.add_argument("--overrides", default=None, help="JSON string of overrides")
    parser.add_argument("--keep-temp", action="store_true", help="Keep temporary files")
    args = parser.parse_args()

    return run_pjob_in_background(
        pjob_code=args.pjob_code,
        execution_id=args.execution_id,
        overrides_json=args.overrides,
        keep_temp=args.keep_temp,
    )


if __name__ == "__main__":
    sys.exit(main())
